language: cpp

compiler:
  - clang
  - gcc

dist: trusty

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcppunit-dev

install: true

script:
  - make run_tests
