language: cpp

compiler:
  - clang
  - gcc

dist: xenial

branches:
  only:
    - master
    - v1.2.x

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libcppunit-dev

install: true

script:
  - make run_tests
